#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
	
	filemanager = "nerdtree"
	enable_filetree_gitstatus = true
	enable_vimfiler_welcome = false
	enable_filetree_status = true
	filetree_direction = "right"
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "oceanicnext"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
	guifont = "VictorMono Nerd Font:h11"
    statusline_separator = "fire"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true

#LAYERS SPACEVIM AND OTHERS

[[layers]]
name = "core#statusline"
enable = false

[[layers]]
name = "colorscheme"
random_theme = false
frequency = "1m"

#[[layers]]
#name = "git"
#git_plugin = 'Fugitve'

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"
[[layers]]
name = "telescope"
[[layers]]
name = "ui"

[[layers]]
name =  "checkers"

[[layers]]
name = "lang#actionscript"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

#**********************************************************************************************#
#							     CUSTOMS PLUGINS											   #
#**********************************************************************************************#
[[custom_plugins]]
repo = "nvim-telescope/telescope-file-browser.nvim"
merged = false

[[custom_plugins]]
repo = "https://github.com/simeji/winresizer.git"
merged = false

[[custom_plugins]]
repo = "https://github.com/vim-airline/vim-airline.git"
merged = 0

[[custom_plugins]]
repo = "https://github.com/vim-airline/vim-airline-themes.git"
merged = 0

[[custom_plugins]]
repo = "https://github.com/ryanoasis/vim-devicons.git"
merged = 0

[[custom_plugins]]
repo = "https://github.com/tiagofumo/vim-nerdtree-syntax-highlight.git"
merged = 0

[[custom_plugins]]
repo = "https://github.com/lambdalisue/battery.vim.git"
merged = 0

[[custom_plugins]]
repo = "https://github.com/tpope/vim-fugitive.git"
merged = 0

[[custom_plugins]]
repo = "https://github.com/42Paris/42header.git"
merged = 0
