#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
	filemanager = "nerdtree"
	enable_filetree_gitstatus = true
	enable_vimfiler_welcome = true
	filetree_direction = "right"
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "OceanicNext"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "fire"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
[[layers]]
name = "incsearch"

[[layers]]
name = "colorscheme"
random_theme = true
frequency = "1m"

[[layers]]
name = "git"
git_plugin = 'Fugitve'

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"
[[layers]]
name = "telescope"
[[layers]]
name = "ui"

[[layers]]
name =  "checkers"

[[layers]]
name = "lang#actionscript"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[custom_plugins]]
repo = "https://github.com/mhartington/oceanic-next.git"
merged = false

[[custom_plugins]]
repo = "nvim-telescope/telescope-file-browser.nvim"
merged = false
